### ISSUE TITLE
Model XHR requests do not send cookies

### ISSUE THREAD

**Issue by fabioberger** [go-humble/humble#2]
If you want to use a session model, or any REST API request which requires the browser cookies to be sent with the request, this is not currently supported. This should be configurable somehow.

**Comment by albrow** [comment]
In the develop branch, we've re-written the model package to use net/http instead of xhr (and also renamed the model package to "rest"). One thing we still need to do is make the requests sent by the rest package configurable. This includes sending cookies and additional headers. This is on our radar and we'll work on it soon as we finish rewriting some other core components.

**Comment by albrow** [comment]
Moved to https://github.com/go-humble/rest/issues/4
